# Generated by Django 4.2.9 on 2024-03-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('Provider_ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Provider_Short_Name', models.CharField(max_length=40)),
                ('Provider_Name', models.CharField(max_length=120)),
            ],
        ),
    ]
